// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace GameStore.DAL.Migrations
{
    public sealed partial class Fix1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fix1));
        
        string IMigrationMetadata.Id
        {
            get { return "201503241237393_Fix1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
